version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    container_name: api
    ports:
      - 3002:3000
    volumes:
      - ./.env:/opt/app/.env
    networks:
      - myNetwork
    depends_on:
      - rmq

  app:
    build: 
      context: .
      dockerfile: ./apps/app/Dockerfile
    restart: always
    container_name: app
    ports:
      - 3001:80
    networks:
      - myNetwork

  rmq:
    image: rabbitmq:3.11.11-management
    restart: always
    environment:
      - RABBIRMQ_DEFAULT_USER=admin
      - RABBIRMQ_DEFAULT_PASS=admin
  
  converter:
    build: 
      context: .
      dockerfile: ./apps/converter/Dockerfile
    restart: always
    container_name: converter
    volumes:
      - ./.env:/opt/app/.env
    networks:
      - myNetwork
    depends_on:
      - rmq


networks:
  myNetwork:
    driver: bridge
